version: '3'
services:
  cinemanow-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    command: bash -c "/opt/mssql/bin/sqlservr & sleep 30 && for f in /docker-entrypoint-initdb.d/*.sql; do echo \"Processing $$f\" && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P QWElkj132! -i \"$$f\"; done & wait"
    networks:
      - cinemanownet
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "QWElkj132!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  cinemanow-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__CinemaNowConnection=Server=cinemanow-sql,1433;Database=IB200033;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5199:5199
    networks:
      - cinemanownet
    links:
      - cinemanow-sql
    depends_on:
      cinemanow-sql:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./CinemaNow.API/Images
        target: /app/Images
      
networks:
  cinemanownet:
    driver: bridge